### ISSUE TITLE
Error when `Run haythem/public-ip@v1.2` 

### ISSUE THREAD

**Issue by Jonasb8** [haythem/public-ip#15]
**Describe the bug**
Error on `Run haythem/public-ip@v1.2` 

**To Reproduce**
Run the example code in a github action workflow

```
jobs:
  ipv4:
    runs-on: ubuntu-latest

    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.1

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
```

**Screenshots**
![Capture d’écran 2021-10-25 à 10 53 31](https://user-images.githubusercontent.com/36473160/138665771-6118b4d6-f8d9-4e33-b274-1e7c03793834.png)
