### ISSUE TITLE
ETIMEDOUT and ECONNRESET when running this action

### ISSUE THREAD

**Issue by patryk-b-jrdltd** [haythem/public-ip#23]
It appears that there is some issue with this actions.
The errors described below appears around 50% of the time.

```
Run haythem/public-ip@v1.3
  with:
    maxRetries: 5
Error: read ECONNRESET
```
and
```
Run haythem/public-ip@v1.3
  with:
    maxRetries: 5
Error: connect ETIMEDOUT 104.237.62.212:443
```

From the source code I can see that you fetch the IP from an external site. Maybe adding some backup sites to get the IP would be a better approach, since the error appears to be caused by that site?

**Comment by john-mcnamee** [comment]
I'm hitting the exact same issue using `haythem/public-ip@v1.2` 
Started earlier today

**Comment by tedparagon** [comment]
Same issue happening to me about half of the time. I have not been able to recreate any failures manually by hitting https://api.ipify.org?format=json directly.

**Comment by haythem** [comment]
Hello,

I'm looking into it. I'll keep you posted.

**Comment by kp-tim-rutte** [comment]
I have the same experience using haythem/public-ip@v1.3.

**Comment by carl-perry** [comment]
Same issue today with v1.2 and v1.3

**Comment by Matze0900** [comment]
We are facing the same issue today

**Comment by amalsgit** [comment]
Saw the same issue couple of times today 😬

**Comment by adamkowalczyk-vocovo** [comment]
This issue is also affecting us

**Comment by haythem** [comment]
Hello everybody,

I'm sorry for the inconvenience. After investigating for some time, it appears that the ipify APIs is complaining about the request randomly. I'm trying to reach out to the owner of service. In the mean time, I'll be building and hosting my own server for IP resolution.

I'll keep you posted. Hang tight.

**Comment by Ugikie** [comment]
Any updates on this? Seems I am also still getting the issue

**Comment by jromero-pg** [comment]
For what it's worth, the `@actions/http-client` [doesn't handle retries for connection issues](https://github.com/actions/toolkit/blob/a91ee0b497d90e7352290ea416f4403e7792aacf/packages/http-client/src/index.ts#L350) (rejects [here](https://github.com/actions/toolkit/blob/a91ee0b497d90e7352290ea416f4403e7792aacf/packages/http-client/src/index.ts#L462)) such as what we are experiencing here.

**Comment by sidpremkumar** [comment]
Any update here? Seeing the same issue on my end 😭

**Comment by sinwoobang** [comment]
Same here, just re-tried and worked though :)

**Comment by pd2xsl** [comment]
Any news on this chaps? Is becoming quite the issue for us?

**Comment by pd2xsl** [comment]
@haythem have you put this project aside? If so please let us know so we can fork into a new project and create a fixable instance. There is a PR awaiting approval to resolve the issue.

Any kind of feedback much would be appreciated.

**Comment by sr523** [comment]
@pd2xsl did you end up forking this? Issue has been cropping up more and more lately

**Comment by pd2xsl** [comment]
@sr523 Nope not yet. Might be good to move forward with it though which is shame.

**Comment by tamas-kr** [comment]
I ended up deploying an azure function app to get around these issues. I retrieve the IP with curl in the YML files:
```
ip=$(curl -s https://example.azurewebsites.net/api/ip?code=xxx)
echo "IP: ${ip}"
```
You can get the github runner's IP address from the `X-Forwarded-For` HTTP header.

**Comment by haythem** [comment]
Hello everyone,

Sorry for the late response, I've been very busy lately with my daily job. I've already created the server and I'm trying to make some time to deploy it (probably this week-end).

**Comment by talr** [comment]
I have the same problem.
Tal

**Comment by frank-navara** [comment]
I'm running into the same issue. Is there any update regards deploying the back-up server? Thanks for all your work into this Action!

**Comment by sylus** [comment]
Had the same problem as well using the following P.R. and switching to the forked action resolved it for me ftm:

https://github.com/haythem/public-ip/pull/24

**Comment by DamienDennehy** [comment]
I too have had issues with this recently. I've created a workaround for Linux based runners using Cloudflare and a built in command using bash. Both are used here as a comparison. 

```
    - name: Get Public IP (cloudflare-ip)
      id: cloudflare-ip
      run: | 
        ipv4=$(dig +short -4 txt ch whoami.cloudflare @1.0.0.1)
        echo "ipv4=$ipv4" >> $GITHUB_OUTPUT
      
    - name: Get Public IP (public-ip)
      id: public-ip
      uses: haythem/public-ip@v1.3

    - name: Log IP
      run: |
        echo IP Using haythem/public-ip: ${{ steps.public-ip.outputs.ipv4 }}
        echo IP Using cloudflare: ${{ steps.cloudflare-ip.outputs.ipv4 }}
```
 
In general both respond in a second or two, but today I saw this action take 1m20s to respond where Cloudflare responded in one second.

**Comment by malimohub** [comment]
Seems like this worked for me. This url seems busted https://api.ipify.org?format=json with it answering requests every now and again. Also see notes about data format for second url response. Hope this helps someone. Can use my forked action if need be here 10ure-devs/10ure-public-ip@v1.2
<img width="486" alt="Screen Shot 2023-06-15 at 11 10 21 AM" src="https://github.com/haythem/public-ip/assets/13194858/2a78c456-65fb-44e1-98d3-d5124deb1a73">

**Comment by lantrix** [comment]
It has started to become a big blocker in some actions for me.

Therefore I solved it by stopping using this and writing a simple curl command to get my IP from the URL of my choice.
Based upon the GitHub documentation https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

```yaml
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    outputs:
      ip: ${{ steps.publicip.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Get Public IP
        id: publicip
        run: |
          response=$(curl -s canhazip.com)
          echo "value='$response'" >> "$GITHUB_OUTPUT"

      - name: Allowlist GH Actions runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id SG-12345678 \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.publicip.outputs.value }}/32
```

**Comment by lantrix** [comment]
It has started to become a big blocker in some actions for me.

LIke @DamienDennehy I solved it by stopping using this and writing a simple curl command to get my IP from the URL of my choice. Based upon the GitHub documentation for [Defining outputs for jobs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs)

I can get an IP from any service, in this case `canhazip.com` and pass it as an output with the key `ip` to another step.

The ID of the step generating the IP address has a name of `publicip` and by echoing the result of the curl:

```shell
echo "ip='$response'" >> "$GITHUB_OUTPUT"
```

the IP address can be referenced in another step as `steps.publicip.outputs.ip`.


```yaml
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: sg-06d03c9f12345678
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-actions-role
          aws-region: ca-central-1

      - name: Get Public IP
        id: publicip
        run: |
          response=$(curl -s canhazip.com)
          echo "ip='$response'" >> "$GITHUB_OUTPUT"

      - name: Allowlist GH Actions runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.publicip.outputs.ip }}/32
```

Works very well.

![Screenshot 2023-06-19 at 14 29 14](https://github.com/haythem/public-ip/assets/117008/596b7bd9-9c14-438f-a585-bde92933fc08)
